# Generated by Django 5.1.6 on 2025-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMMON_USER', 'Common_user')], default='ADMIN', max_length=50),
        ),
    ]
