# Generated by Django 5.1.6 on 2025-03-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
