# Generated by Django 5.1.6 on 2025-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('order_price', models.IntegerField()),
                ('books_info', models.CharField(max_length=5000)),
            ],
        ),
    ]
